#This is not the right place for storing passwords!

# application name
APP_NAME: Borrow

# feature toggles
FT_LIBRARY: true
FT_SEARCH: true
FT_BORROW: true

FT_AUTO_FILL: false
FT_EDIT_ACCOUNT: false
FT_TYPES: false
