#This is not the right place for storing passwords!

# application name
APP_NAME: Media

# feature toggles
FT_LIBRARY: true
FT_SEARCH: true
FT_BORROW: true
FT_EDIT_ACCOUNT: true

FT_AUTO_FILL: false
FT_TYPES: false
