development:
  adapter: postgresql
  encoding: unicode
  database: media_development
  pool: 5
  username: media
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: media_test
  pool: 5
  username: media
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: media_production
  pool: 5
  username: media
  password:
