User.create!([
  {email: "tester1@tester.de", password: "12345678", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2013-12-02 20:22:18", last_sign_in_at: "2013-11-29 15:52:13", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "mrx1"},
  {email: "tester2@tester.de", password: "12345678", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2013-12-02 20:24:25", last_sign_in_at: "2013-12-02 20:24:25", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "mrx2"},
  {email: "tester3@tester.de", password: "12345678", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2013-12-08 12:18:08", last_sign_in_at: "2013-12-08 12:18:08", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "mrx3"},
  {email: "tester4@tester.de", password: "12345678", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2013-12-08 12:23:27", last_sign_in_at: "2013-12-08 12:23:27", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "mrx4"},
  {email: "tester5@tester.de", password: "12345678", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2013-12-08 12:25:09", last_sign_in_at: "2013-12-08 12:25:09", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "mrx5"},
  {email: "tester6@tester.de", password: "12345678", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2014-02-04 20:34:45", last_sign_in_at: "2014-02-04 19:10:23", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "mrx6"},
  {email: "tester7@tester.de", password: "12345678", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2013-12-16 20:58:29", last_sign_in_at: "2013-12-16 20:58:29", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "mrx7"}
])
Type.create!([
  {name: "DVD"},
  {name: "Blu-ray"},
  {name: "Playstation 3 Game"},
  {name: "Book"},
  {name: "Playstation 2 Game"},
  {name: "Stream"}
])
MediaItem.create!([
  {title: "The Last Of Us", link: "http://www.thelastofus.com/", type_id: 3, user_id: 1},
  {title: "Gangster Squad", link: "http://www.imdb.com/title/tt1321870/", type_id: 2, user_id: 1},
  {title: "Notting Hill", link: "", type_id: 1, user_id: 1},
  {title: "James Bond - Skyfall", link: "", type_id: 1, user_id: 1},
  {title: "The Dark Knight Rises", link: "", type_id: 2, user_id: 1},
  {title: "Shaun of the dead", link: "http://www.imdb.com/title/tt0365748", type_id: 1, user_id: 1},
  {title: "How I met your mother - Season 1", link: "", type_id: 1, user_id: 1},
  {title: "Der Medicus", link: "http://de.wikipedia.org/wiki/Der_Medicus", type_id: 4, user_id: 1},
  {title: "Kokowäh", link: "", type_id: 1, user_id: 2},
  {title: "Fear and loathing in Las Vegas ", link: "http://m.youtube.com/watch?v=9mbf7Q7mXOw", type_id: 1, user_id: 3},
  {title: "The Dark Knight", link: "http://www.imdb.com/title/tt0468569/", type_id: 1, user_id: 1},
  {title: "Blub", link: "", type_id: 2, user_id: 1},
  {title: "YYY", link: "", type_id: 2, user_id: 1},
  {title: "YYY", link: "", type_id: 1, user_id: 1},
  {title: "Blub", link: "", type_id: 4, user_id: 1},
  {title: "Blub", link: "", type_id: 3, user_id: 1},
  {title: "XXX", link: "", type_id: 2, user_id: 1},
  {title: "fdafasasdfasdf", link: "", type_id: 2, user_id: 7},
  {title: "hutzel", link: "h:a", type_id: 5, user_id: 1},
  {title: "Kokowähaaaaaaa", link: "", type_id: 5, user_id: 1},
  {title: "Babedibubi", link: "http://www.youtube.com/watch?v=9JhuOicPFZY", type_id: 2, user_id: 1},
  {title: " Family Guy - Bullfrog", link: "http://www.youtube.com/watch?v=DXHaCEhOiWU", type_id: 6, user_id: 1},
  {title: "Family Guy - Speaking italian", link: "http://www.youtube.com/watch?v=9JhuOicPFZY", type_id: 6, user_id: 1}
])
Ownership.create!([
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 2},
  {user_id: 1, media_item_id: 3},
  {user_id: 1, media_item_id: 5},
  {user_id: 1, media_item_id: 6},
  {user_id: 1, media_item_id: 7},
  {user_id: 1, media_item_id: 8},
  {user_id: 2, media_item_id: 9},
  {user_id: 3, media_item_id: 10},
  {user_id: 1, media_item_id: 12},
  {user_id: 1, media_item_id: 15},
  {user_id: 1, media_item_id: 16},
  {user_id: 1, media_item_id: 18},
  {user_id: 1, media_item_id: 20},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 10},
  {user_id: 1, media_item_id: 9},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 17},
  {user_id: 7, media_item_id: 1},
  {user_id: 1, media_item_id: 4},
  {user_id: 7, media_item_id: 21},
  {user_id: 1, media_item_id: 17},
  {user_id: 1, media_item_id: 10},
  {user_id: 1, media_item_id: 10},
  {user_id: 1, media_item_id: 22},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 1},
  {user_id: 1, media_item_id: 22},
  {user_id: 1, media_item_id: 22}
])
BorrowReceipt.create!([
  {owner_id: 1, borrower_id: 3, media_item_id: 1},
  {owner_id: 1, borrower_id: 2, media_item_id: 1},
  {owner_id: 1, borrower_id: 3, media_item_id: 1},
  {owner_id: 1, borrower_id: 3, media_item_id: 17},
  {owner_id: 1, borrower_id: 5, media_item_id: 1},
  {owner_id: 1, borrower_id: 5, media_item_id: 2},
  {owner_id: 1, borrower_id: 5, media_item_id: 3},
  {owner_id: 1, borrower_id: 5, media_item_id: 5},
  {owner_id: 1, borrower_id: 6, media_item_id: 12},
  {owner_id: 1, borrower_id: 5, media_item_id: 22}
])
